[package]
name = "paysec-crypto-rustcrypto"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "RustCrypto cryptographic provider for paysec."

[dependencies]
aes.workspace = true
cbc.workspace = true
cmac.workspace = true
paysec-crypto.workspace = true

[dev-dependencies]
hex.workspace = true