[package]
name = "paysec-crypto-rustcrypto"
version = "0.2.2"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

description = "RustCrypto AES cryptographic provider for paysec."
documentation = "https://docs.rs/paysec-crypto-rustcrypto"
readme = "README.md"
keywords = [
    "payments",
    "cryptography",
    "aes",
    "rustcrypto",
]
categories = ["cryptography"]

[dependencies]
aes.workspace = true
cbc.workspace = true
cmac.workspace = true
paysec-crypto.workspace = true

[dev-dependencies]
hex.workspace = true
