[workspace]
members = [
    "crates/paysec",
    "crates/paysec-crypto",
    "crates/paysec-crypto-soft-aes",
    "crates/paysec-crypto-rustcrypto",
    "crates/paysec-pinblock",
    "crates/paysec-keyblock",
	"crates/paysec-dukpt",
    "crates/paysec-tr34"
]
resolver = "3"

[workspace.package]
edition = "2024"
rust-version = "1.89"
authors = ["David Schmid <david.schmid@mailbox.org>"]
license = "GPL-3.0"
repository = "https://github.com/5n00py/paysec"

[workspace.dependencies]
hex = "0.4.3"
soft-aes = "0.2.2"

aes = "0.9.3"
cbc = { version = "0.2.1", features = ["alloc"] }
cmac = "0.8.0"

zeroize = "1.9.0"

rsa = { version = "0.9.10", features = ["sha2"] }
sha2 = { version = "0.10.9", features = ["oid"] }
rand_core = { version = "0.6.4", features = ["getrandom"] }

cms = { version = "0.2.3", default-features = false, features = ["alloc", "std"] }
der = { version = "0.7", features = ["alloc", "derive", "std"] }

x509-cert = { version = "0.2.5", default-features = false, features = ["std"] }

pkcs1 = { version = "0.7.5", default-features = false, features = ["std"] }
spki = { version = "0.7.3", default-features = false, features = ["std"] }

paysec-crypto = { version = "0.3.0", path = "crates/paysec-crypto" }
paysec-crypto-soft-aes = { version = "0.2.1", path = "crates/paysec-crypto-soft-aes" }
paysec-crypto-rustcrypto = { version = "0.3.0", path = "crates/paysec-crypto-rustcrypto" }
paysec-pinblock = { version = "0.2.1", path = "crates/paysec-pinblock" }
paysec-keyblock = { version = "0.2.1", path = "crates/paysec-keyblock" }
paysec-dukpt = { version = "0.1.0", path = "crates/paysec-dukpt" }
paysec-tr34 = { version = "0.1.0", path = "crates/paysec-tr34" }
