[workspace]
members = [
    "crates/paysec",
    "crates/paysec-crypto",
    "crates/paysec-crypto-soft-aes",
    "crates/paysec-pinblock",
    "crates/paysec-keyblock",
]
resolver = "3"

[workspace.package]
version = "0.2.0"
edition = "2024"
rust-version = "1.89"
authors = ["David Schmid <david.schmid@mailbox.org>"]
license = "GPL-3.0"
repository = "https://github.com/5n00py/paysec"

[workspace.dependencies]
hex = "0.4.3"
soft-aes = "0.2.2"

paysec-crypto = {
    version = "0.2.0",
    path = "crates/paysec-crypto",
}

paysec-crypto-soft-aes = {
    version = "0.2.0",
    path = "crates/paysec-crypto-soft-aes",
}

paysec-pinblock = {
    version = "0.2.0",
    path = "crates/paysec-pinblock",
}

paysec-keyblock = {
    version = "0.2.0",
    path = "crates/paysec-keyblock",
}
