[package]
name = "paysec-tr34"
version = "0.1.1"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

description = "TR-34 processing for payment security applications."
documentation = "https://docs.rs/paysec-tr34"
readme = "README.md"
keywords = [
    "payments",
    "payment-security",
    "tr34",
    "cryptography",
    "key-transport",
]
categories = ["cryptography"]

[dependencies]
cms.workspace = true
der.workspace = true
paysec-crypto.workspace = true
pkcs1.workspace = true
sha2.workspace = true
spki.workspace = true
x509-cert.workspace = true
zeroize.workspace = true

[dev-dependencies]
hex.workspace = true
paysec-crypto-rustcrypto.workspace = true
rand_core.workspace = true
rsa.workspace = true