[package]
name = "paysec"
version = "0.3.0"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

description = "Payment security standards library."
documentation = "https://docs.rs/paysec"
readme = "README.md"
keywords = [
    "payment-security",
    "pin-block",
    "tr31",
    "cryptography",
    "dukpt",
]
categories = ["cryptography"]

[dependencies]
paysec-pinblock.workspace = true
paysec-keyblock.workspace = true
paysec-dukpt.workspace = true