[package]
name = "paysec-crypto-soft-aes"
version = "0.2.1"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

description = "Software AES cryptographic provider for paysec based on soft-aes."
documentation = "https://docs.rs/paysec-crypto-soft-aes"
readme = "README.md"
keywords = [
    "payments",
    "cryptography",
    "aes",
    "soft-aes",
]
categories = ["cryptography"]

[dependencies]
paysec-crypto.workspace = true
soft-aes.workspace = true

[dev-dependencies]
hex.workspace = true
