[package]
name = "paysec-pinblock"
version = "0.2.1"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

description = "ISO 9564 PIN block processing for payment security applications."
documentation = "https://docs.rs/paysec-pinblock"
readme = "README.md"
keywords = [
    "payments",
    "payment-security",
    "pin-block",
    "iso9564",
]
categories = ["cryptography"]

[dependencies]
hex.workspace = true
paysec-crypto.workspace = true
zeroize.workspace = true

[dev-dependencies]
paysec-crypto-rustcrypto.workspace = true
paysec-crypto-soft-aes.workspace = true
