[package]
name = "paysec-keyblock"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Key block functionality for payment security standards."

[dependencies]
hex.workspace = true
paysec-crypto.workspace = true
zeroize.workspace = true

[dev-dependencies]
paysec-crypto-rustcrypto.workspace = true
paysec-crypto-soft-aes.workspace = true