[package]
name = "paysec-keyblock"
version = "0.2.1"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

description = "TR-31 key block processing for payment security applications."
documentation = "https://docs.rs/paysec-keyblock"
readme = "README.md"
keywords = [
    "payments",
    "payment-security",
    "key-block",
    "tr31",
    "cryptography",
]
categories = ["cryptography"]

[dependencies]
hex.workspace = true
paysec-crypto.workspace = true
zeroize.workspace = true

[dev-dependencies]
paysec-crypto-rustcrypto.workspace = true
paysec-crypto-soft-aes.workspace = true
